version: "3.9"
services:
  web:
    environment:
      PYTHONUNBUFFERED: 1
      MONGODB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGODB_HOSTNAME: ${DB_HOSTNAME}
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGODB_HOSTNAME: ${DB_HOSTNAME}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js