version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: kj
      MONGO_INITDB_ROOT_PASSWORD: solar-system
      MONGODB_HOSTNAME: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb: